//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akimbus
{
    public partial class CoursesAdd
    {
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator valTitle;
        protected global::System.Web.UI.WebControls.TextBox txtCredits;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator valCredits;
        protected global::System.Web.UI.WebControls.RangeValidator rangeCredits;
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator valDepartment;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
